---
- hosts: localhost
  collections:
    - netapp.ontap
#  vars:
#    netapp_hostname: 172.16.250.10
#    netapp_username: admin
#    netapp_password: redhat12
  tasks:
  - name: Check import netapp-lib
    na_ontap_debug:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
