---
- hosts: localhost
  collections:
    - netapp.ontap

  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: present
      name: "{{ vserver_name }}"
      root_volume: "{{ vol_name }}"
      root_volume_aggregate: "{{ aggr_name }}"
      root_volume_security_style: mixed
      hostname: "{{ netapp_hostname }}"
      username: "{{ ansible_env.ANSIBLE_NET_USERNAME }}"
      password: "{{ ansible_env.ANSIBLE_NET_PASSWORD }}"
      https: yes
      validate_certs: false
