---
- hosts: localhost
  collections:
    - netapp.ontap

  tasks:
  - name: Check import netapp-lib
    na_ontap_debug:
      hostname: "{{ netapp_hostname }}"
      username: "{{ ansible_env.ANSIBLE_NET_USERNAME }}"
      password: "{{ ansible_env.ANSIBLE_NET_PASSWORD }}"
      https: true
      validate_certs: false
