---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action
  vars:
    hostname: 172.16.250.10
    username: admin
    password: redhat12
    vserver: svm0
    aggr: aggr1
    vol_name: ansibleVol
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: default
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
