---
- hosts: localhost
  collections:
    - netapp.ontap

  vars:
    hostname: 172.16.250.10
    username: admin
    password: redhat12
    vserver: svm0
    aggr: aggr1
    vol_name: ansibleVol

  tasks:
    - name: Volume Delete
      na_ontap_volume:
        state: absent
        name: "{{ vol_name }}"
        aggregate_name: "{{ aggr }}"
        vserver: "{{ vserver }}"
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false

    - name: Delete SVM
      na_ontap_svm:
        state: absent
        name: svm0
        root_volume: svm0_root
        root_volume_aggregate: aggr1
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: Delete Aggregate
      na_ontap_aggregate:
        state: absent
        service_state: offline
        unmount_volumes: yes
        name: "{{ aggr }}"
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
