---
- hosts: localhost
  collections:
    - netapp.ontap

  tasks:
  - name: run ONTAP gather facts for all subsets
    na_ontap_rest_info:
      hostname: "{{ netapp_hostname }}"
#      hostname: "c1n1"
      username: "{{ ansible_env.ANSIBLE_NET_USERNAME }}"
      password: "{{ ansible_env.ANSIBLE_NET_PASSWORD }}"
      https: true
      validate_certs: false
      use_rest: Always
#      fields:
#        - 'name'
#        - "!uuid"
      gather_subset:
      - aggregate_info
    register: device_info
  - name: show info gathered
    debug:
      msg: '{{ aggregate_report|from_yaml }}'
      vars:
        aggregate_report: |-
          {% for record in ontap_info["storage/aggregates"].records %}
          - "Aggregate Name: {{ record.name }}"
          {% endfor %}