---
- hosts: localhost
  collections:
    - netapp.ontap

  tasks:
  - name: run ONTAP gather facts for all subsets
    netapp.ontap.na_ontap_rest_info:
      hostname: "{{ netapp_hostname }}"
      username: "{{ ansible_env.ANSIBLE_NET_USERNAME }}"
      password: "{{ ansible_env.ANSIBLE_NET_PASSWORD }}"
      https: true
      validate_certs: false
      use_rest: Always
      fields:
        - 'name'
        - "!uuid"
      gather_subset:
      - aggregate_info
    register: device_info
  - name: show info gathered
    debug:
#      msg: "{{ device_info| json_query('\"ontap_info.storage/aggregates\"') }}"
      msg: "{{ device_info }}"
