---
- hosts: localhost
  collections:
    - netapp.ontap

  tasks:
  - name: run ONTAP gather facts for all subsets
    na_ontap_info:
      hostname: "c1n1"
      username: "admin"
      password: "redhat12"
    register: ontap_info
  - debug:
      msg: "{{ ontap_info.ontap_info }}"
